### ISSUE TITLE
Autodoc generated links on HuggingFace documentation include "src" folder so link to source doesn't work

### ISSUE THREAD

**Issue by emosy** [bitsandbytes-foundation/bitsandbytes#1274]
### System Info

Website-only issue:
Chrome 126.0.6478.127 (Official Build) (arm64) 

### Reproduction

Go to https://huggingface.co/docs/bitsandbytes/main/en/reference/nn/embeddings#bitsandbytes.nn.StableEmbedding and click on `<source>` for `Embedding`.
It will go to https://github.com/bitsandbytes-foundation/bitsandbytes/blob/main/src/bitsandbytes/nn/modules.py#L132, which is a "404 - page not found" since the file is no longer at `src/...`.

### Expected behavior

The link should go to https://github.com/bitsandbytes-foundation/bitsandbytes/blob/main/bitsandbytes/nn/modules.py#L132

I believe the link is generated by Autodoc here: https://github.com/bitsandbytes-foundation/bitsandbytes/blob/main/docs/source/reference/nn/embeddings.mdx

**Comment by Titus-von-Koeller** [comment]
Thanks @emosy for raising this, really appreciated! Will look into this and fix it soon.

**Comment by Titus-von-Koeller** [comment]
it's working now, just validated that the `<source>` link works correctly, see https://huggingface.co/docs/bitsandbytes/main/en/reference/nn/embeddings

thanks again @emosy ❤️

**Comment by emosy** [comment]
Thank you! :P
