### ISSUE TITLE
Release 0.44.0 does not belong to the current repository

### ISSUE THREAD

**Issue by ccoulombe** [bitsandbytes-foundation/bitsandbytes#1370]
### System Info

None

### Reproduction

This commit is not part of the current repo : https://github.com/bitsandbytes-foundation/bitsandbytes/commit/9841697480a9684cfd90fc0f252aad82c26717ae

Thus the tagged commit is not : https://github.com/bitsandbytes-foundation/bitsandbytes/tree/v0.44.0

The head is : https://github.com/bitsandbytes-foundation/bitsandbytes/commits/main/

### Expected behavior

Correctly tag and release the v0.44.0 for the current repository

**Comment by matthewdouglas** [comment]
Hi @ccoulombe 
The release commit is pushed now.

**Comment by ccoulombe** [comment]
@matthewdouglas Thanks!
I think it is pertinent that it is also in `main`. It is currently is not present, yet the tag exists : https://github.com/bitsandbytes-foundation/bitsandbytes/commits/main/
