### ISSUE TITLE
ARM Runners December 2024

### ISSUE THREAD

**Issue by johnnynunez** [bitsandbytes-foundation/bitsandbytes#1390]
### Feature request

Github Actions will publish ARM Runners in GITHUB. 
Totally free December 2024:
https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/
https://github.blog/changelog/2024-09-03-github-actions-arm64-linux-and-windows-runners-are-now-generally-available/

taking account this for next dockers and the future of computation:
https://wccftech.com/nvidia-x-mediatek-ai-pc-soc-debut-second-half-2025/

### Motivation

Compatible library with arm device like grace and jetson agx orin

### Your contribution

loading

**Comment by matthewdouglas** [comment]
We'll track the aarch64 build here: #1437.
